"""Reviewed production catalog contract for runtime tables adopted from legacy storage.

These tables existed before the fully reviewed Alembic graph, but they are now
active runtime infrastructure with a physically observed production shape.  At
Step 49A they stop being opaque preserved legacy objects and become part of the
exact head contract.
"""

ADOPTED_RUNTIME_TABLES = {
    "client_domain_credential",
    "client_domain_status",
    "client_command",
    "remote_desktop_session",
    "remote_desktop_session_event",
}

ADOPTED_RUNTIME_COLUMNS = {
    "client_domain_credential": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "domain": {"data_type": "character varying", "default": None, "length": 40, "nullable": False, "udt_name": "varchar"},
        "secret_hash": {"data_type": "text", "default": None, "length": None, "nullable": False, "udt_name": "text"},
        "token_version": {"data_type": "integer", "default": "0", "length": None, "nullable": False, "udt_name": "int4"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "last_used_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "revoked_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
    },
    "client_domain_status": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "domain": {"data_type": "character varying", "default": None, "length": 40, "nullable": False, "udt_name": "varchar"},
        "schema_version": {"data_type": "integer", "default": "1", "length": None, "nullable": False, "udt_name": "int4"},
        "observed_state": {"data_type": "character varying", "default": "'unknown'::character varying", "length": 80, "nullable": False, "udt_name": "varchar"},
        "status_payload": {"data_type": "jsonb", "default": None, "length": None, "nullable": False, "udt_name": "jsonb"},
        "agent_version": {"data_type": "character varying", "default": None, "length": 80, "nullable": True, "udt_name": "varchar"},
        "boot_id": {"data_type": "character varying", "default": None, "length": 128, "nullable": True, "udt_name": "varchar"},
        "credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "reported_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
    },
    "client_command": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "domain": {"data_type": "character varying", "default": None, "length": 40, "nullable": False, "udt_name": "varchar"},
        "command_type": {"data_type": "character varying", "default": None, "length": 100, "nullable": False, "udt_name": "varchar"},
        "schema_version": {"data_type": "integer", "default": "1", "length": None, "nullable": False, "udt_name": "int4"},
        "payload": {"data_type": "jsonb", "default": None, "length": None, "nullable": False, "udt_name": "jsonb"},
        "payload_encryption_key_id": {"data_type": "character varying", "default": None, "length": 120, "nullable": True, "udt_name": "varchar"},
        "idempotency_key": {"data_type": "character varying", "default": None, "length": 200, "nullable": False, "udt_name": "varchar"},
        "requested_by_user_id": {"data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"},
        "requested_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "available_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "expires_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "status": {"data_type": "character varying", "default": "'queued'::character varying", "length": 30, "nullable": False, "udt_name": "varchar"},
        "claim_token_hash": {"data_type": "character varying", "default": None, "length": 64, "nullable": True, "udt_name": "varchar"},
        "claimed_by_credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": True, "udt_name": "varchar"},
        "claimed_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "lease_expires_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "attempt_count": {"data_type": "integer", "default": "0", "length": None, "nullable": False, "udt_name": "int4"},
        "max_attempts": {"data_type": "integer", "default": "3", "length": None, "nullable": False, "udt_name": "int4"},
        "completed_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "result": {"data_type": "jsonb", "default": None, "length": None, "nullable": True, "udt_name": "jsonb"},
        "error_code": {"data_type": "character varying", "default": None, "length": 100, "nullable": True, "udt_name": "varchar"},
        "error_message": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
    },
    "remote_desktop_session": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "requested_by_user_id": {"data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"},
        "source_ip": {"data_type": "character varying", "default": None, "length": 64, "nullable": True, "udt_name": "varchar"},
        "user_agent": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "connected_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "last_activity_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "expires_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "disconnected_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "status": {"data_type": "character varying", "default": "'authorized'::character varying", "length": 30, "nullable": False, "udt_name": "varchar"},
        "close_reason": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
    },
    "remote_desktop_session_event": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "remote_desktop_session_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "event_type": {"data_type": "character varying", "default": None, "length": 80, "nullable": False, "udt_name": "varchar"},
        "actor_user_id": {"data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"},
        "credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": True, "udt_name": "varchar"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "details": {"data_type": "jsonb", "default": None, "length": None, "nullable": False, "udt_name": "jsonb"},
    },
}

ADOPTED_RUNTIME_CONSTRAINTS = {
    "ck_client_domain_credential_domain": "CHECK (domain::text = ANY (ARRAY['status'::character varying, 'display'::character varying, 'livestream'::character varying, 'remote_desktop'::character varying, 'terminal'::character varying, 'system'::character varying]::text[]))",
    "ck_client_domain_credential_token_version": "CHECK (token_version >= 0)",
    "client_domain_credential_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES client(id)",
    "client_domain_credential_pkey": "PRIMARY KEY (id)",
    "uq_client_domain_credential_client_domain": "UNIQUE (client_id, domain)",
    "ck_client_domain_status_domain": "CHECK (domain::text = ANY (ARRAY['status'::character varying, 'display'::character varying, 'livestream'::character varying, 'remote_desktop'::character varying, 'terminal'::character varying, 'system'::character varying]::text[]))",
    "ck_client_domain_status_schema_version": "CHECK (schema_version >= 1)",
    "client_domain_status_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES client(id)",
    "client_domain_status_credential_id_fkey": "FOREIGN KEY (credential_id) REFERENCES client_domain_credential(id)",
    "client_domain_status_pkey": "PRIMARY KEY (id)",
    "uq_client_domain_status_client_domain": "UNIQUE (client_id, domain)",
    "ck_client_command_attempt_nonnegative": "CHECK (attempt_count >= 0)",
    "ck_client_command_domain": "CHECK (domain::text = ANY (ARRAY['display'::character varying, 'livestream'::character varying, 'system'::character varying]::text[]))",
    "ck_client_command_expiry_order": "CHECK (expires_at > requested_at)",
    "ck_client_command_max_attempts": "CHECK (max_attempts >= 1 AND max_attempts <= 10)",
    "ck_client_command_schema_version": "CHECK (schema_version >= 1)",
    "ck_client_command_status": "CHECK (status::text = ANY (ARRAY['queued'::character varying, 'claimed'::character varying, 'succeeded'::character varying, 'failed'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[]))",
    "client_command_claimed_by_credential_id_fkey": "FOREIGN KEY (claimed_by_credential_id) REFERENCES client_domain_credential(id)",
    "client_command_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES client(id)",
    "client_command_pkey": "PRIMARY KEY (id)",
    "client_command_requested_by_user_id_fkey": 'FOREIGN KEY (requested_by_user_id) REFERENCES "user"(id) ON DELETE SET NULL',
    "uq_client_command_idempotency": "UNIQUE (client_id, domain, idempotency_key)",
    "ck_remote_desktop_session_expiry_order": "CHECK (expires_at > created_at)",
    "ck_remote_desktop_session_status": "CHECK (status::text = ANY (ARRAY['requested'::character varying, 'authorized'::character varying, 'connected'::character varying, 'disconnected'::character varying, 'expired'::character varying, 'revoked'::character varying, 'failed'::character varying]::text[]))",
    "remote_desktop_session_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES remote_desktop_client(id)",
    "remote_desktop_session_pkey": "PRIMARY KEY (id)",
    "remote_desktop_session_requested_by_user_id_fkey": 'FOREIGN KEY (requested_by_user_id) REFERENCES "user"(id) ON DELETE SET NULL',
    "remote_desktop_session_event_actor_user_id_fkey": 'FOREIGN KEY (actor_user_id) REFERENCES "user"(id) ON DELETE SET NULL',
    "remote_desktop_session_event_credential_id_fkey": "FOREIGN KEY (credential_id) REFERENCES remote_desktop_credential(id)",
    "remote_desktop_session_event_pkey": "PRIMARY KEY (id)",
    "remote_desktop_session_event_remote_desktop_session_id_fkey": "FOREIGN KEY (remote_desktop_session_id) REFERENCES remote_desktop_session(id)",
}

ADOPTED_RUNTIME_INDEXES = {
    "client_domain_credential_pkey": "CREATE UNIQUE INDEX client_domain_credential_pkey ON public.client_domain_credential USING btree (id)",
    "ix_client_domain_credential_active": "CREATE INDEX ix_client_domain_credential_active ON public.client_domain_credential USING btree (client_id, domain, revoked_at)",
    "ix_client_domain_credential_client_id": "CREATE INDEX ix_client_domain_credential_client_id ON public.client_domain_credential USING btree (client_id)",
    "ix_client_domain_credential_domain": "CREATE INDEX ix_client_domain_credential_domain ON public.client_domain_credential USING btree (domain)",
    "ix_client_domain_credential_last_used_at": "CREATE INDEX ix_client_domain_credential_last_used_at ON public.client_domain_credential USING btree (last_used_at)",
    "ix_client_domain_credential_revoked_at": "CREATE INDEX ix_client_domain_credential_revoked_at ON public.client_domain_credential USING btree (revoked_at)",
    "uq_client_domain_credential_client_domain": "CREATE UNIQUE INDEX uq_client_domain_credential_client_domain ON public.client_domain_credential USING btree (client_id, domain)",
    "client_domain_status_pkey": "CREATE UNIQUE INDEX client_domain_status_pkey ON public.client_domain_status USING btree (id)",
    "ix_client_domain_status_client_id": "CREATE INDEX ix_client_domain_status_client_id ON public.client_domain_status USING btree (client_id)",
    "ix_client_domain_status_domain": "CREATE INDEX ix_client_domain_status_domain ON public.client_domain_status USING btree (domain)",
    "ix_client_domain_status_reported": "CREATE INDEX ix_client_domain_status_reported ON public.client_domain_status USING btree (domain, reported_at)",
    "ix_client_domain_status_reported_at": "CREATE INDEX ix_client_domain_status_reported_at ON public.client_domain_status USING btree (reported_at)",
    "uq_client_domain_status_client_domain": "CREATE UNIQUE INDEX uq_client_domain_status_client_domain ON public.client_domain_status USING btree (client_id, domain)",
    "client_command_pkey": "CREATE UNIQUE INDEX client_command_pkey ON public.client_command USING btree (id)",
    "ix_client_command_available_at": "CREATE INDEX ix_client_command_available_at ON public.client_command USING btree (available_at)",
    "ix_client_command_claim": "CREATE INDEX ix_client_command_claim ON public.client_command USING btree (client_id, domain, status, available_at, expires_at)",
    "ix_client_command_client_id": "CREATE INDEX ix_client_command_client_id ON public.client_command USING btree (client_id)",
    "ix_client_command_domain": "CREATE INDEX ix_client_command_domain ON public.client_command USING btree (domain)",
    "ix_client_command_expires_at": "CREATE INDEX ix_client_command_expires_at ON public.client_command USING btree (expires_at)",
    "ix_client_command_lease": "CREATE INDEX ix_client_command_lease ON public.client_command USING btree (status, lease_expires_at)",
    "ix_client_command_lease_expires_at": "CREATE INDEX ix_client_command_lease_expires_at ON public.client_command USING btree (lease_expires_at)",
    "ix_client_command_requested_by_user_id": "CREATE INDEX ix_client_command_requested_by_user_id ON public.client_command USING btree (requested_by_user_id)",
    "ix_client_command_status": "CREATE INDEX ix_client_command_status ON public.client_command USING btree (status)",
    "uq_client_command_idempotency": "CREATE UNIQUE INDEX uq_client_command_idempotency ON public.client_command USING btree (client_id, domain, idempotency_key)",
    "remote_desktop_session_pkey": "CREATE UNIQUE INDEX remote_desktop_session_pkey ON public.remote_desktop_session USING btree (id)",
    "ix_remote_desktop_session_client_id": "CREATE INDEX ix_remote_desktop_session_client_id ON public.remote_desktop_session USING btree (client_id)",
    "ix_remote_desktop_session_client_status": "CREATE INDEX ix_remote_desktop_session_client_status ON public.remote_desktop_session USING btree (client_id, status)",
    "ix_remote_desktop_session_expires_at": "CREATE INDEX ix_remote_desktop_session_expires_at ON public.remote_desktop_session USING btree (expires_at)",
    "ix_remote_desktop_session_expiry": "CREATE INDEX ix_remote_desktop_session_expiry ON public.remote_desktop_session USING btree (status, expires_at)",
    "ix_remote_desktop_session_requested_by_user_id": "CREATE INDEX ix_remote_desktop_session_requested_by_user_id ON public.remote_desktop_session USING btree (requested_by_user_id)",
    "ix_remote_desktop_session_status": "CREATE INDEX ix_remote_desktop_session_status ON public.remote_desktop_session USING btree (status)",
    "remote_desktop_session_event_pkey": "CREATE UNIQUE INDEX remote_desktop_session_event_pkey ON public.remote_desktop_session_event USING btree (id)",
    "ix_remote_desktop_session_event_created_at": "CREATE INDEX ix_remote_desktop_session_event_created_at ON public.remote_desktop_session_event USING btree (created_at)",
    "ix_remote_desktop_session_event_event_type": "CREATE INDEX ix_remote_desktop_session_event_event_type ON public.remote_desktop_session_event USING btree (event_type)",
    "ix_remote_desktop_session_event_timeline": "CREATE INDEX ix_remote_desktop_session_event_timeline ON public.remote_desktop_session_event USING btree (remote_desktop_session_id, created_at)",
}
