"""Frozen catalog contract for the verified Display production baseline."""
from __future__ import annotations

BASELINE_REVISION = '20260712_30d_display_base'
EXPECTED_HEAD_REVISION = '20260814_41a_livestream_v2'
EXPECTED_TABLES = {'audit_logs',
 'calendarmarking',
 'client',
 'enrollmenttoken',
 'livestream_viewer_lease',
 'organization',
 'organizationlogo',
 'organizationseasontimes',
 'refresh_tokens',
 'user'}
EXPECTED_COLUMNS = {'audit_logs': {'action': {'data_type': 'character varying', 'default': None, 'length': 100, 'nullable': False, 'udt_name': 'varchar'},
                'actor_organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'actor_role': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
                'actor_user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'actor_username': {'data_type': 'character varying',
                                   'default': None,
                                   'length': None,
                                   'nullable': True,
                                   'udt_name': 'varchar'},
                'created_at': {'data_type': 'timestamp without time zone',
                               'default': None,
                               'length': None,
                               'nullable': False,
                               'udt_name': 'timestamp'},
                'details': {'data_type': 'json', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'json'},
                'entity_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'entity_label': {'data_type': 'character varying',
                                 'default': None,
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'varchar'},
                'entity_type': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
                'id': {'data_type': 'integer',
                       'default': "nextval('audit_logs_id_seq'::regclass)",
                       'length': None,
                       'nullable': False,
                       'udt_name': 'int4'},
                'is_critical': {'data_type': 'boolean', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'bool'},
                'request_id': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': True, 'udt_name': 'varchar'},
                'request_ip': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
                'retain_until': {'data_type': 'timestamp without time zone',
                                 'default': None,
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'timestamp'},
                'retention_days': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'severity': {'data_type': 'character varying', 'default': None, 'length': 20, 'nullable': False, 'udt_name': 'varchar'},
                'status': {'data_type': 'character varying', 'default': None, 'length': 40, 'nullable': False, 'udt_name': 'varchar'},
                'target_organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'target_user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                'target_username': {'data_type': 'character varying',
                                    'default': None,
                                    'length': None,
                                    'nullable': True,
                                    'udt_name': 'varchar'},
                'user_agent': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'}},
 'calendarmarking': {'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
                     'id': {'data_type': 'integer',
                            'default': "nextval('calendarmarking_id_seq'::regclass)",
                            'length': None,
                            'nullable': False,
                            'udt_name': 'int4'},
                     'markings': {'data_type': 'jsonb', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'jsonb'},
                     'season': {'data_type': 'text', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'text'}},
 'client': {'active_network_interface': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'active_network_ip': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'active_network_mac': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'active_network_type': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'browser_refresh_interval_sec': {'data_type': 'integer',
                                             'default': '900',
                                             'length': None,
                                             'nullable': True,
                                             'udt_name': 'int4'},
            'chrome_color': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'chrome_last_updated': {'data_type': 'timestamp without time zone',
                                    'default': None,
                                    'length': None,
                                    'nullable': True,
                                    'udt_name': 'timestamp'},
            'chrome_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'chrome_step': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'client_secret_created_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'client_secret_hash': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_secret_revoked_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'client_token_version': {'data_type': 'integer', 'default': '0', 'length': None, 'nullable': False, 'udt_name': 'int4'},
            'client_update_allow_downgrade': {'data_type': 'boolean',
                                              'default': 'false',
                                              'length': None,
                                              'nullable': False,
                                              'udt_name': 'bool'},
            'client_update_applied_deployment_sequence': {'data_type': 'integer',
                                                          'default': '0',
                                                          'length': None,
                                                          'nullable': False,
                                                          'udt_name': 'int4'},
            'client_update_deployment_sequence': {'data_type': 'integer',
                                                  'default': '0',
                                                  'length': None,
                                                  'nullable': False,
                                                  'udt_name': 'int4'},
            'client_update_error': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_update_finished_at': {'data_type': 'timestamp without time zone',
                                          'default': None,
                                          'length': None,
                                          'nullable': True,
                                          'udt_name': 'timestamp'},
            'client_update_message': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_update_reason': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_update_requested_at': {'data_type': 'timestamp without time zone',
                                           'default': None,
                                           'length': None,
                                           'nullable': True,
                                           'udt_name': 'timestamp'},
            'client_update_started_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'client_update_status': {'data_type': 'text', 'default': "'ready'::text", 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_update_target_release_sequence': {'data_type': 'integer',
                                                      'default': None,
                                                      'length': None,
                                                      'nullable': True,
                                                      'udt_name': 'int4'},
            'client_update_target_version': {'data_type': 'text',
                                             'default': "'latest'::text",
                                             'length': None,
                                             'nullable': True,
                                             'udt_name': 'text'},
            'client_version': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_version_patch': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'client_version_updated_at': {'data_type': 'timestamp without time zone',
                                          'default': None,
                                          'length': None,
                                          'nullable': True,
                                          'udt_name': 'timestamp'},
            'created_at': {'data_type': 'timestamp without time zone',
                           'default': 'CURRENT_TIMESTAMP',
                           'length': None,
                           'nullable': False,
                           'udt_name': 'timestamp'},
            'deleted_at': {'data_type': 'timestamp without time zone',
                           'default': None,
                           'length': None,
                           'nullable': True,
                           'udt_name': 'timestamp'},
            'deleted_by_user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'deleted_previous_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'deleted_reason': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'desktop_lockdown_enabled': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'desktop_lockdown_last_applied_at': {'data_type': 'timestamp without time zone',
                                                 'default': None,
                                                 'length': None,
                                                 'nullable': True,
                                                 'udt_name': 'timestamp'},
            'desktop_lockdown_message': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'desktop_lockdown_status': {'data_type': 'text',
                                        'default': "'unknown'::text",
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'text'},
            'desktop_lockdown_updated_at': {'data_type': 'timestamp without time zone',
                                            'default': None,
                                            'length': None,
                                            'nullable': True,
                                            'udt_name': 'timestamp'},
            'diagnostics_updated_at': {'data_type': 'timestamp without time zone',
                                       'default': None,
                                       'length': None,
                                       'nullable': True,
                                       'udt_name': 'timestamp'},
            'system_timezone': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'ntp_enabled': {'data_type': 'boolean', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'ntp_synchronized': {'data_type': 'boolean', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'client_time_utc': {'data_type': 'timestamp without time zone',
                                'default': None,
                                'length': None,
                                'nullable': True,
                                'udt_name': 'timestamp'},
            'clock_drift_seconds': {'data_type': 'double precision', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'float8'},
            'time_sync_status': {'data_type': 'text',
                                 'default': "'unknown'::text",
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'text'},
            'time_sync_message': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'display_detected_outputs': {'data_type': 'json', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'json'},
            'display_detected_updated_at': {'data_type': 'timestamp without time zone',
                                            'default': None,
                                            'length': None,
                                            'nullable': True,
                                            'udt_name': 'timestamp'},
            'display_resolution_action': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'display_resolution_current_height': {'data_type': 'integer',
                                                  'default': None,
                                                  'length': None,
                                                  'nullable': True,
                                                  'udt_name': 'int4'},
            'display_resolution_current_output': {'data_type': 'text',
                                                  'default': None,
                                                  'length': None,
                                                  'nullable': True,
                                                  'udt_name': 'text'},
            'display_resolution_current_refresh_rate': {'data_type': 'double precision',
                                                        'default': None,
                                                        'length': None,
                                                        'nullable': True,
                                                        'udt_name': 'float8'},
            'display_resolution_current_width': {'data_type': 'integer',
                                                 'default': None,
                                                 'length': None,
                                                 'nullable': True,
                                                 'udt_name': 'int4'},
            'display_resolution_error': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'display_resolution_height': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'display_resolution_last_applied_at': {'data_type': 'timestamp without time zone',
                                                   'default': None,
                                                   'length': None,
                                                   'nullable': True,
                                                   'udt_name': 'timestamp'},
            'display_resolution_mode': {'data_type': 'text',
                                        'default': "'auto'::text",
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'text'},
            'display_resolution_preset': {'data_type': 'text',
                                          'default': "'auto'::text",
                                          'length': None,
                                          'nullable': True,
                                          'udt_name': 'text'},
            'display_resolution_refresh_rate': {'data_type': 'double precision',
                                                'default': None,
                                                'length': None,
                                                'nullable': True,
                                                'udt_name': 'float8'},
            'display_resolution_rotation': {'data_type': 'text',
                                            'default': "'normal'::text",
                                            'length': None,
                                            'nullable': True,
                                            'udt_name': 'text'},
            'display_resolution_status': {'data_type': 'text',
                                          'default': "'unknown'::text",
                                          'length': None,
                                          'nullable': True,
                                          'udt_name': 'text'},
            'display_resolution_updated_at': {'data_type': 'timestamp without time zone',
                                              'default': None,
                                              'length': None,
                                              'nullable': True,
                                              'udt_name': 'timestamp'},
            'display_resolution_width': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'enrollment_token_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'id': {'data_type': 'integer',
                   'default': "nextval('client_id_seq'::regclass)",
                   'length': None,
                   'nullable': False,
                   'udt_name': 'int4'},
            'isOnline': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'kiosk_url': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'lan_ip_address': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'lan_mac_address': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'last_boot_at': {'data_type': 'timestamp without time zone',
                             'default': None,
                             'length': None,
                             'nullable': True,
                             'udt_name': 'timestamp'},
            'last_boot_id': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'last_power_event': {'data_type': 'character varying',
                                 'default': None,
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'varchar'},
            'last_power_event_at': {'data_type': 'timestamp without time zone',
                                    'default': None,
                                    'length': None,
                                    'nullable': True,
                                    'udt_name': 'timestamp'},
            'last_power_event_source': {'data_type': 'character varying',
                                        'default': None,
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'varchar'},
            'last_reboot_started_at': {'data_type': 'timestamp without time zone',
                                       'default': None,
                                       'length': None,
                                       'nullable': True,
                                       'udt_name': 'timestamp'},
            'last_seen': {'data_type': 'timestamp without time zone',
                          'default': None,
                          'length': None,
                          'nullable': True,
                          'udt_name': 'timestamp'},
            'last_shutdown_started_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'livestream_desired_state': {'data_type': 'character varying',
                                         'default': "'stopped'::character varying",
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'varchar'},
            'livestream_last_error': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'livestream_last_segment': {'data_type': 'timestamp without time zone',
                                        'default': None,
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'timestamp'},
            'livestream_process_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'livestream_status': {'data_type': 'character varying', 'default': None, 'length': 50, 'nullable': True, 'udt_name': 'varchar'},
            'livestream_stop_reason': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'livestream_viewer_count': {'data_type': 'integer', 'default': '0', 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'livestream_viewer_last_seen': {'data_type': 'timestamp without time zone',
                                            'default': None,
                                            'length': None,
                                            'nullable': True,
                                            'udt_name': 'timestamp'},
            'local_management_action': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'local_management_desired_hostname': {'data_type': 'text',
                                                  'default': None,
                                                  'length': None,
                                                  'nullable': True,
                                                  'udt_name': 'text'},
            'local_management_error': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'local_management_finished_at': {'data_type': 'timestamp without time zone',
                                             'default': None,
                                             'length': None,
                                             'nullable': True,
                                             'udt_name': 'timestamp'},
            'local_management_message': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'local_management_request_id': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'local_management_requested_at': {'data_type': 'timestamp without time zone',
                                              'default': None,
                                              'length': None,
                                              'nullable': True,
                                              'udt_name': 'timestamp'},
            'local_management_secret': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'local_management_started_at': {'data_type': 'timestamp without time zone',
                                            'default': None,
                                            'length': None,
                                            'nullable': True,
                                            'udt_name': 'timestamp'},
            'local_management_status': {'data_type': 'text',
                                        'default': "'ready'::text",
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'text'},
            'locality': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'machine_id': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'name': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'varchar'},
            'organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'pending_chrome_action': {'data_type': 'character varying',
                                      'default': None,
                                      'length': 20,
                                      'nullable': True,
                                      'udt_name': 'varchar'},
            'pending_chrome_action_source': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'pending_os_update': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'pending_reboot': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'pending_shutdown': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': True, 'udt_name': 'bool'},
            'restored_at': {'data_type': 'timestamp without time zone',
                            'default': None,
                            'length': None,
                            'nullable': True,
                            'udt_name': 'timestamp'},
            'restored_by_user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'school': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'service_admin_terminal_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_browser_guard_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_calendar_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_clientflow_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_kiosk_x11_guard_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_livestream_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_local_reboot_reporter_status': {'data_type': 'text',
                                                     'default': None,
                                                     'length': None,
                                                     'nullable': True,
                                                     'udt_name': 'text'},
            'service_local_shutdown_reporter_status': {'data_type': 'text',
                                                       'default': None,
                                                       'length': None,
                                                       'nullable': True,
                                                       'udt_name': 'text'},
            'service_remote_desktop_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_remote_terminal_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_selfupdate_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'service_ubuntu_update_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'sort_order': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'state': {'data_type': 'character varying',
                      'default': "'normal'::character varying",
                      'length': 32,
                      'nullable': True,
                      'udt_name': 'varchar'},
            'status': {'data_type': 'character varying',
                       'default': "'pending'::character varying",
                       'length': None,
                       'nullable': True,
                       'udt_name': 'varchar'},
            'ubuntu_update_error': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'ubuntu_update_finished_at': {'data_type': 'timestamp without time zone',
                                          'default': None,
                                          'length': None,
                                          'nullable': True,
                                          'udt_name': 'timestamp'},
            'ubuntu_update_message': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'ubuntu_update_package_count': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'ubuntu_update_progress': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'ubuntu_update_reboot_required': {'data_type': 'boolean',
                                              'default': None,
                                              'length': None,
                                              'nullable': True,
                                              'udt_name': 'bool'},
            'ubuntu_update_started_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'ubuntu_update_status': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'ubuntu_update_step': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
            'ubuntu_update_updated_at': {'data_type': 'timestamp without time zone',
                                         'default': None,
                                         'length': None,
                                         'nullable': True,
                                         'udt_name': 'timestamp'},
            'ubuntu_updates_available': {'data_type': 'integer', 'default': '0', 'length': None, 'nullable': True, 'udt_name': 'int4'},
            'ubuntu_version': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'uptime': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'wifi_ip_address': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
            'wifi_mac_address': {'data_type': 'character varying',
                                 'default': None,
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'varchar'}},
 'enrollmenttoken': {'code_hash': {'data_type': 'character varying',
                                   'default': None,
                                   'length': None,
                                   'nullable': False,
                                   'udt_name': 'varchar'},
                     'code_preview': {'data_type': 'character varying',
                                      'default': None,
                                      'length': None,
                                      'nullable': True,
                                      'udt_name': 'varchar'},
                     'created_at': {'data_type': 'timestamp without time zone',
                                    'default': None,
                                    'length': None,
                                    'nullable': False,
                                    'udt_name': 'timestamp'},
                     'created_by_user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                     'expires_at': {'data_type': 'timestamp without time zone',
                                    'default': None,
                                    'length': None,
                                    'nullable': False,
                                    'udt_name': 'timestamp'},
                     'id': {'data_type': 'integer',
                            'default': "nextval('enrollmenttoken_id_seq'::regclass)",
                            'length': None,
                            'nullable': False,
                            'udt_name': 'int4'},
                     'note': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
                     'organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
                     'revoked_at': {'data_type': 'timestamp without time zone',
                                    'default': None,
                                    'length': None,
                                    'nullable': True,
                                    'udt_name': 'timestamp'},
                     'used_at': {'data_type': 'timestamp without time zone',
                                 'default': None,
                                 'length': None,
                                 'nullable': True,
                                 'udt_name': 'timestamp'},
                     'used_by_client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'}},
 'livestream_viewer_lease': {'client_id': {'data_type': 'integer',
                                            'default': None,
                                            'length': None,
                                            'nullable': False,
                                            'udt_name': 'int4'},
                             'expires_at': {'data_type': 'timestamp without time zone',
                                            'default': None,
                                            'length': None,
                                            'nullable': False,
                                            'udt_name': 'timestamp'},
                             'id': {'data_type': 'integer',
                                    'default': "nextval('livestream_viewer_lease_id_seq'::regclass)",
                                    'length': None,
                                    'nullable': False,
                                    'udt_name': 'int4'},
                             'last_seen_at': {'data_type': 'timestamp without time zone',
                                              'default': None,
                                              'length': None,
                                              'nullable': False,
                                              'udt_name': 'timestamp'},
                             'source': {'data_type': 'character varying',
                                        'default': None,
                                        'length': 120,
                                        'nullable': True,
                                        'udt_name': 'varchar'},
                             'viewer_id': {'data_type': 'character varying',
                                           'default': None,
                                           'length': 120,
                                           'nullable': False,
                                           'udt_name': 'varchar'}},
 'organization': {'day_times': {'data_type': 'jsonb',
                                'default': "jsonb_build_object('monday', jsonb_build_object('status', 'on', 'onTime', '09:00', 'offTime', '20:00'), "
                                           "'tuesday', jsonb_build_object('status', 'on', 'onTime', '09:00', 'offTime', '20:00'), "
                                           "'wednesday', jsonb_build_object('status', 'on', 'onTime', '09:00', 'offTime', '20:00'), "
                                           "'thursday', jsonb_build_object('status', 'on', 'onTime', '09:00', 'offTime', '20:00'), "
                                           "'friday', jsonb_build_object('status', 'on', 'onTime', '09:00', 'offTime', '20:00'), "
                                           "'saturday', jsonb_build_object('status', 'off'), 'sunday', jsonb_build_object('status', 'off'))",
                                'length': None,
                                'nullable': False,
                                'udt_name': 'jsonb'},
                  'id': {'data_type': 'integer',
                         'default': "nextval('school_id_seq'::regclass)",
                         'length': None,
                         'nullable': False,
                         'udt_name': 'int4'},
                  'name': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'varchar'}},
 'organizationlogo': {'content_type': {'data_type': 'character varying',
                                       'default': None,
                                       'length': None,
                                       'nullable': False,
                                       'udt_name': 'varchar'},
                      'data': {'data_type': 'bytea', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'bytea'},
                      'filename': {'data_type': 'character varying',
                                   'default': None,
                                   'length': None,
                                   'nullable': False,
                                   'udt_name': 'varchar'},
                      'organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
                      'size_bytes': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
                      'uploaded_at': {'data_type': 'timestamp without time zone',
                                      'default': 'now()',
                                      'length': None,
                                      'nullable': False,
                                      'udt_name': 'timestamp'},
                      'uploaded_by_user_id': {'data_type': 'integer',
                                              'default': None,
                                              'length': None,
                                              'nullable': True,
                                              'udt_name': 'int4'}},
 'organizationseasontimes': {'day_times': {'data_type': 'jsonb',
                                           'default': "jsonb_build_object('monday', jsonb_build_object('status', 'on', 'onTime', '09:00', "
                                                      "'offTime', '20:00'), 'tuesday', jsonb_build_object('status', 'on', 'onTime', '09:00', "
                                                      "'offTime', '20:00'), 'wednesday', jsonb_build_object('status', 'on', 'onTime', '09:00', "
                                                      "'offTime', '20:00'), 'thursday', jsonb_build_object('status', 'on', 'onTime', '09:00', "
                                                      "'offTime', '20:00'), 'friday', jsonb_build_object('status', 'on', 'onTime', '09:00', "
                                                      "'offTime', '20:00'), 'saturday', jsonb_build_object('status', 'off'), 'sunday', "
                                                      "jsonb_build_object('status', 'off'))",
                                           'length': None,
                                           'nullable': False,
                                           'udt_name': 'jsonb'},
                             'id': {'data_type': 'integer',
                                    'default': "nextval('schoolseasontimes_id_seq'::regclass)",
                                    'length': None,
                                    'nullable': False,
                                    'udt_name': 'int4'},
                             'organization_id': {'data_type': 'integer',
                                                 'default': None,
                                                 'length': None,
                                                 'nullable': False,
                                                 'udt_name': 'int4'},
                             'season': {'data_type': 'text', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'text'}},
 'refresh_tokens': {'created_at': {'data_type': 'timestamp without time zone',
                                   'default': None,
                                   'length': None,
                                   'nullable': False,
                                   'udt_name': 'timestamp'},
                    'created_ip': {'data_type': 'character varying',
                                   'default': None,
                                   'length': 45,
                                   'nullable': True,
                                   'udt_name': 'varchar'},
                    'expires_at': {'data_type': 'timestamp without time zone',
                                   'default': None,
                                   'length': None,
                                   'nullable': False,
                                   'udt_name': 'timestamp'},
                    'id': {'data_type': 'integer',
                           'default': "nextval('refresh_tokens_id_seq'::regclass)",
                           'length': None,
                           'nullable': False,
                           'udt_name': 'int4'},
                    'revoked_at': {'data_type': 'timestamp without time zone',
                                   'default': None,
                                   'length': None,
                                   'nullable': True,
                                   'udt_name': 'timestamp'},
                    'session_expires_at': {'data_type': 'timestamp without time zone',
                                           'default': None,
                                           'length': None,
                                           'nullable': True,
                                           'udt_name': 'timestamp'},
                    'token_hash': {'data_type': 'character varying',
                                   'default': None,
                                   'length': 64,
                                   'nullable': False,
                                   'udt_name': 'varchar'},
                    'user_agent': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
                    'user_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'}},
 'user': {'created_at': {'data_type': 'timestamp without time zone',
                         'default': 'now()',
                         'length': None,
                         'nullable': False,
                         'udt_name': 'timestamp'},
          'email': {'data_type': 'character varying',
                    'default': "''::character varying",
                    'length': 255,
                    'nullable': False,
                    'udt_name': 'varchar'},
          'full_name': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
          'hashed_password': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'varchar'},
          'id': {'data_type': 'integer',
                 'default': "nextval('user_id_seq'::regclass)",
                 'length': None,
                 'nullable': False,
                 'udt_name': 'int4'},
          'is_active': {'data_type': 'boolean', 'default': 'true', 'length': None, 'nullable': False, 'udt_name': 'bool'},
          'last_login_at': {'data_type': 'timestamp without time zone',
                            'default': None,
                            'length': None,
                            'nullable': True,
                            'udt_name': 'timestamp'},
          'last_login_ip': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
          'must_change_password': {'data_type': 'boolean', 'default': 'false', 'length': None, 'nullable': False, 'udt_name': 'bool'},
          'organization_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
          'password_reset_expires_at': {'data_type': 'timestamp without time zone',
                                        'default': None,
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'timestamp'},
          'password_reset_token_hash': {'data_type': 'character varying',
                                        'default': None,
                                        'length': None,
                                        'nullable': True,
                                        'udt_name': 'varchar'},
          'remarks': {'data_type': 'text', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'text'},
          'role': {'data_type': 'character varying',
                   'default': "'admin'::character varying",
                   'length': None,
                   'nullable': False,
                   'udt_name': 'varchar'},
          'token_version': {'data_type': 'integer', 'default': '0', 'length': None, 'nullable': False, 'udt_name': 'int4'},
          'username': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'varchar'}}}
EXPECTED_CONSTRAINTS = {'audit_logs_pkey': 'PRIMARY KEY (id)',
 'calendarmarking_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
 'calendarmarking_client_season_unique': 'UNIQUE (client_id, season)',
 'calendarmarking_pkey': 'PRIMARY KEY (id)',
 'client_pkey': 'PRIMARY KEY (id)',
 'client_school_id_fkey': 'FOREIGN KEY (organization_id) REFERENCES organization(id)',
 'enrollmenttoken_created_by_user_id_fkey': 'FOREIGN KEY (created_by_user_id) REFERENCES "user"(id)',
 'enrollmenttoken_pkey': 'PRIMARY KEY (id)',
 'enrollmenttoken_school_id_fkey': 'FOREIGN KEY (organization_id) REFERENCES organization(id)',
 'enrollmenttoken_used_by_client_id_fkey': 'FOREIGN KEY (used_by_client_id) REFERENCES client(id)',
 'livestream_viewer_lease_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
 'livestream_viewer_lease_pkey': 'PRIMARY KEY (id)',
 'organizationlogo_organization_id_fkey': 'FOREIGN KEY (organization_id) REFERENCES organization(id)',
 'organizationlogo_pkey': 'PRIMARY KEY (organization_id)',
 'organizationlogo_uploaded_by_user_id_fkey': 'FOREIGN KEY (uploaded_by_user_id) REFERENCES "user"(id)',
 'organizationseasontimes_org_season_unique': 'UNIQUE (organization_id, season)',
 'refresh_tokens_pkey': 'PRIMARY KEY (id)',
 'refresh_tokens_user_id_fkey': 'FOREIGN KEY (user_id) REFERENCES "user"(id)',
 'school_pkey': 'PRIMARY KEY (id)',
 'schoolseasontimes_pkey': 'PRIMARY KEY (id)',
 'schoolseasontimes_school_id_fkey': 'FOREIGN KEY (organization_id) REFERENCES organization(id)',
 'user_pkey': 'PRIMARY KEY (id)',
 'uq_livestream_viewer_lease_client_viewer': 'UNIQUE (client_id, viewer_id)',
 'user_school_id_fkey': 'FOREIGN KEY (organization_id) REFERENCES organization(id)',
 'users_role_check': "CHECK (role::text = ANY (ARRAY['superadmin'::character varying, 'admin'::character varying, 'bruger'::character "
                     "varying, 'viewer'::character varying]::text[]))"}
EXPECTED_INDEXES = {'audit_logs_pkey': 'CREATE UNIQUE INDEX audit_logs_pkey ON public.audit_logs USING btree (id)',
 'calendarmarking_client_season_unique': 'CREATE UNIQUE INDEX calendarmarking_client_season_unique ON public.calendarmarking USING btree (client_id, season)',
 'calendarmarking_pkey': 'CREATE UNIQUE INDEX calendarmarking_pkey ON public.calendarmarking USING btree (id)',
 'client_pkey': 'CREATE UNIQUE INDEX client_pkey ON public.client USING btree (id)',
 'enrollmenttoken_pkey': 'CREATE UNIQUE INDEX enrollmenttoken_pkey ON public.enrollmenttoken USING btree (id)',
 'idx_calendarmarking_client_id': 'CREATE INDEX idx_calendarmarking_client_id ON public.calendarmarking USING btree (client_id)',
 'idx_calendarmarking_season': 'CREATE INDEX idx_calendarmarking_season ON public.calendarmarking USING btree (season)',
 'idx_client_deleted_at': 'CREATE INDEX idx_client_deleted_at ON public.client USING btree (deleted_at)',
 'idx_client_org_deleted_at': 'CREATE INDEX idx_client_org_deleted_at ON public.client USING btree (organization_id, deleted_at)',
 'idx_client_sort_order': 'CREATE INDEX idx_client_sort_order ON public.client USING btree (sort_order)',
 'idx_client_status_deleted_at': 'CREATE INDEX idx_client_status_deleted_at ON public.client USING btree (status, deleted_at)',
 'ix_audit_logs_action': 'CREATE INDEX ix_audit_logs_action ON public.audit_logs USING btree (action)',
 'ix_audit_logs_actor_user_id': 'CREATE INDEX ix_audit_logs_actor_user_id ON public.audit_logs USING btree (actor_user_id)',
 'ix_audit_logs_created_at': 'CREATE INDEX ix_audit_logs_created_at ON public.audit_logs USING btree (created_at)',
 'ix_audit_logs_entity': 'CREATE INDEX ix_audit_logs_entity ON public.audit_logs USING btree (entity_type, entity_id)',
 'ix_audit_logs_entity_id': 'CREATE INDEX ix_audit_logs_entity_id ON public.audit_logs USING btree (entity_id)',
 'ix_audit_logs_entity_type': 'CREATE INDEX ix_audit_logs_entity_type ON public.audit_logs USING btree (entity_type)',
 'ix_audit_logs_is_critical': 'CREATE INDEX ix_audit_logs_is_critical ON public.audit_logs USING btree (is_critical)',
 'ix_audit_logs_request_id': 'CREATE INDEX ix_audit_logs_request_id ON public.audit_logs USING btree (request_id)',
 'ix_audit_logs_retain_until': 'CREATE INDEX ix_audit_logs_retain_until ON public.audit_logs USING btree (retain_until)',
 'ix_audit_logs_severity': 'CREATE INDEX ix_audit_logs_severity ON public.audit_logs USING btree (severity)',
 'ix_audit_logs_target_user_id': 'CREATE INDEX ix_audit_logs_target_user_id ON public.audit_logs USING btree (target_user_id)',
 'ix_client_last_boot_id': 'CREATE INDEX ix_client_last_boot_id ON public.client USING btree (last_boot_id)',
 'ix_client_last_power_event_at': 'CREATE INDEX ix_client_last_power_event_at ON public.client USING btree (last_power_event_at)',
 'ix_enrollmenttoken_code_preview': 'CREATE INDEX ix_enrollmenttoken_code_preview ON public.enrollmenttoken USING btree (code_preview)',
 'ix_livestream_viewer_lease_client_id': 'CREATE INDEX ix_livestream_viewer_lease_client_id ON public.livestream_viewer_lease USING btree (client_id)',
 'ix_livestream_viewer_lease_expires_at': 'CREATE INDEX ix_livestream_viewer_lease_expires_at ON public.livestream_viewer_lease USING btree (expires_at)',
 'ix_organizationlogo_content_type': 'CREATE INDEX ix_organizationlogo_content_type ON public.organizationlogo USING btree (content_type)',
 'ix_refresh_tokens_expires_at': 'CREATE INDEX ix_refresh_tokens_expires_at ON public.refresh_tokens USING btree (expires_at)',
 'ix_refresh_tokens_revoked_at': 'CREATE INDEX ix_refresh_tokens_revoked_at ON public.refresh_tokens USING btree (revoked_at)',
 'ix_refresh_tokens_session_expires_at': 'CREATE INDEX ix_refresh_tokens_session_expires_at ON public.refresh_tokens USING btree '
                                         '(session_expires_at)',
 'ix_refresh_tokens_token_hash': 'CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON public.refresh_tokens USING btree (token_hash)',
 'ix_refresh_tokens_user_id': 'CREATE INDEX ix_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id)',
 'ix_school_name': 'CREATE UNIQUE INDEX ix_school_name ON public.organization USING btree (name)',
 'ix_schoolseasontimes_school_id': 'CREATE INDEX ix_schoolseasontimes_school_id ON public.organizationseasontimes USING btree '
                                   '(organization_id)',
 'ix_schoolseasontimes_season': 'CREATE INDEX ix_schoolseasontimes_season ON public.organizationseasontimes USING btree (season)',
 'ix_user_last_login_at': 'CREATE INDEX ix_user_last_login_at ON public."user" USING btree (last_login_at)',
 'ix_user_password_reset_expires_at': 'CREATE INDEX ix_user_password_reset_expires_at ON public."user" USING btree '
                                      '(password_reset_expires_at)',
 'ix_user_password_reset_token_hash': 'CREATE INDEX ix_user_password_reset_token_hash ON public."user" USING btree '
                                      '(password_reset_token_hash)',
 'livestream_viewer_lease_pkey': 'CREATE UNIQUE INDEX livestream_viewer_lease_pkey ON public.livestream_viewer_lease USING btree (id)',
 'organizationlogo_pkey': 'CREATE UNIQUE INDEX organizationlogo_pkey ON public.organizationlogo USING btree (organization_id)',
 'organizationseasontimes_org_season_unique': 'CREATE UNIQUE INDEX organizationseasontimes_org_season_unique ON '
                                              'public.organizationseasontimes USING btree (organization_id, season)',
 'refresh_tokens_pkey': 'CREATE UNIQUE INDEX refresh_tokens_pkey ON public.refresh_tokens USING btree (id)',
 'school_pkey': 'CREATE UNIQUE INDEX school_pkey ON public.organization USING btree (id)',
 'schoolseasontimes_pkey': 'CREATE UNIQUE INDEX schoolseasontimes_pkey ON public.organizationseasontimes USING btree (id)',
 'uq_livestream_viewer_lease_client_viewer': 'CREATE UNIQUE INDEX uq_livestream_viewer_lease_client_viewer ON public.livestream_viewer_lease USING btree (client_id, viewer_id)',
 'user_pkey': 'CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id)'}
EXPECTED_SEQUENCES = {'audit_logs_id_seq',
 'calendarmarking_id_seq',
 'client_id_seq',
 'enrollmenttoken_id_seq',
 'livestream_viewer_lease_id_seq',
 'refresh_tokens_id_seq',
 'school_id_seq',
 'schoolseasontimes_id_seq',
 'user_id_seq'}
EXPECTED_TRIGGERS: set[str] = set()
EXPECTED_EXTENSION_NAMES = {'plpgsql'}
# Step 41A: isolated Livestream v2 extension.  These objects are deliberately
# prefixed and do not reuse the legacy Terminal/Remote Desktop/client-domain
# tables preserved by the production reconciliation path.
EXPECTED_TABLES |= {
    'livestream_v2_agent_status',
    'livestream_v2_command',
    'livestream_v2_credential',
    'livestream_v2_generation',
    'livestream_v2_viewer',
}
EXPECTED_COLUMNS.update({
    'livestream_v2_credential': {
        'id': {'data_type': 'character varying', 'default': None, 'length': 36, 'nullable': False, 'udt_name': 'varchar'},
        'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'domain': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'secret_digest': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'token_version': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'created_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'revoked_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
    },
    'livestream_v2_command': {
        'id': {'data_type': 'character varying', 'default': None, 'length': 36, 'nullable': False, 'udt_name': 'varchar'},
        'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'command_type': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'payload': {'data_type': 'jsonb', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'jsonb'},
        'schema_version': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'state': {'data_type': 'character varying', 'default': None, 'length': 32, 'nullable': False, 'udt_name': 'varchar'},
        'attempts': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'available_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'lease_expires_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'claim_token_digest': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': True, 'udt_name': 'varchar'},
        'result': {'data_type': 'jsonb', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'jsonb'},
        'error_code': {'data_type': 'character varying', 'default': None, 'length': 128, 'nullable': True, 'udt_name': 'varchar'},
        'error_message': {'data_type': 'character varying', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'varchar'},
        'retryable': {'data_type': 'boolean', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'bool'},
        'created_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'updated_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'completed_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
    },
    'livestream_v2_agent_status': {
        'id': {'data_type': 'integer', 'default': "nextval('livestream_v2_agent_status_id_seq'::regclass)", 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'observed_state': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'status_payload': {'data_type': 'jsonb', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'jsonb'},
        'agent_version': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'boot_id': {'data_type': 'character varying', 'default': None, 'length': 128, 'nullable': True, 'udt_name': 'varchar'},
        'updated_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
    },
    'livestream_v2_viewer': {
        'id': {'data_type': 'integer', 'default': "nextval('livestream_v2_viewer_id_seq'::regclass)", 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'viewer_id': {'data_type': 'character varying', 'default': None, 'length': 120, 'nullable': False, 'udt_name': 'varchar'},
        'principal_key': {'data_type': 'character varying', 'default': None, 'length': 160, 'nullable': False, 'udt_name': 'varchar'},
        'source': {'data_type': 'character varying', 'default': None, 'length': 120, 'nullable': True, 'udt_name': 'varchar'},
        'created_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'last_seen_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'ended_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'end_reason': {'data_type': 'character varying', 'default': None, 'length': 32, 'nullable': True, 'udt_name': 'varchar'},
    },
    'livestream_v2_generation': {
        'id': {'data_type': 'character varying', 'default': None, 'length': 36, 'nullable': False, 'udt_name': 'varchar'},
        'client_id': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'int4'},
        'state': {'data_type': 'character varying', 'default': None, 'length': 32, 'nullable': False, 'udt_name': 'varchar'},
        'requested_action': {'data_type': 'character varying', 'default': None, 'length': 64, 'nullable': False, 'udt_name': 'varchar'},
        'created_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': False, 'udt_name': 'timestamp'},
        'started_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'stopped_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'superseded_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'last_upload_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'last_manifest_at': {'data_type': 'timestamp without time zone', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'timestamp'},
        'last_sequence': {'data_type': 'integer', 'default': None, 'length': None, 'nullable': True, 'udt_name': 'int4'},
        'error_code': {'data_type': 'character varying', 'default': None, 'length': 128, 'nullable': True, 'udt_name': 'varchar'},
    },
})
EXPECTED_CONSTRAINTS.update({
    'livestream_v2_credential_pkey': 'PRIMARY KEY (id)',
    'livestream_v2_credential_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
    'livestream_v2_command_pkey': 'PRIMARY KEY (id)',
    'livestream_v2_command_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
    'livestream_v2_agent_status_pkey': 'PRIMARY KEY (id)',
    'livestream_v2_agent_status_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
    'uq_livestream_v2_agent_status_client': 'UNIQUE (client_id)',
    'livestream_v2_viewer_pkey': 'PRIMARY KEY (id)',
    'livestream_v2_viewer_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
    'uq_livestream_v2_viewer_client_viewer': 'UNIQUE (client_id, viewer_id)',
    'livestream_v2_generation_pkey': 'PRIMARY KEY (id)',
    'livestream_v2_generation_client_id_fkey': 'FOREIGN KEY (client_id) REFERENCES client(id)',
})
EXPECTED_INDEXES.update({
    'livestream_v2_credential_pkey': 'CREATE UNIQUE INDEX livestream_v2_credential_pkey ON public.livestream_v2_credential USING btree (id)',
    'ix_livestream_v2_credential_client_id': 'CREATE INDEX ix_livestream_v2_credential_client_id ON public.livestream_v2_credential USING btree (client_id)',
    'ix_livestream_v2_credential_domain': 'CREATE INDEX ix_livestream_v2_credential_domain ON public.livestream_v2_credential USING btree (domain)',
    'ix_livestream_v2_credential_revoked_at': 'CREATE INDEX ix_livestream_v2_credential_revoked_at ON public.livestream_v2_credential USING btree (revoked_at)',
    'ix_livestream_v2_credential_client_active': 'CREATE INDEX ix_livestream_v2_credential_client_active ON public.livestream_v2_credential USING btree (client_id, revoked_at)',
    'livestream_v2_command_pkey': 'CREATE UNIQUE INDEX livestream_v2_command_pkey ON public.livestream_v2_command USING btree (id)',
    'ix_livestream_v2_command_client_id': 'CREATE INDEX ix_livestream_v2_command_client_id ON public.livestream_v2_command USING btree (client_id)',
    'ix_livestream_v2_command_state': 'CREATE INDEX ix_livestream_v2_command_state ON public.livestream_v2_command USING btree (state)',
    'ix_livestream_v2_command_available_at': 'CREATE INDEX ix_livestream_v2_command_available_at ON public.livestream_v2_command USING btree (available_at)',
    'ix_livestream_v2_command_lease_expires_at': 'CREATE INDEX ix_livestream_v2_command_lease_expires_at ON public.livestream_v2_command USING btree (lease_expires_at)',
    'ix_livestream_v2_command_completed_at': 'CREATE INDEX ix_livestream_v2_command_completed_at ON public.livestream_v2_command USING btree (completed_at)',
    'ix_livestream_v2_command_claim': 'CREATE INDEX ix_livestream_v2_command_claim ON public.livestream_v2_command USING btree (client_id, state, available_at, created_at)',
    'livestream_v2_agent_status_pkey': 'CREATE UNIQUE INDEX livestream_v2_agent_status_pkey ON public.livestream_v2_agent_status USING btree (id)',
    'uq_livestream_v2_agent_status_client': 'CREATE UNIQUE INDEX uq_livestream_v2_agent_status_client ON public.livestream_v2_agent_status USING btree (client_id)',
    'ix_livestream_v2_agent_status_client_id': 'CREATE INDEX ix_livestream_v2_agent_status_client_id ON public.livestream_v2_agent_status USING btree (client_id)',
    'ix_livestream_v2_agent_status_updated_at': 'CREATE INDEX ix_livestream_v2_agent_status_updated_at ON public.livestream_v2_agent_status USING btree (updated_at)',
    'livestream_v2_viewer_pkey': 'CREATE UNIQUE INDEX livestream_v2_viewer_pkey ON public.livestream_v2_viewer USING btree (id)',
    'uq_livestream_v2_viewer_client_viewer': 'CREATE UNIQUE INDEX uq_livestream_v2_viewer_client_viewer ON public.livestream_v2_viewer USING btree (client_id, viewer_id)',
    'ix_livestream_v2_viewer_client_id': 'CREATE INDEX ix_livestream_v2_viewer_client_id ON public.livestream_v2_viewer USING btree (client_id)',
    'ix_livestream_v2_viewer_last_seen_at': 'CREATE INDEX ix_livestream_v2_viewer_last_seen_at ON public.livestream_v2_viewer USING btree (last_seen_at)',
    'ix_livestream_v2_viewer_ended_at': 'CREATE INDEX ix_livestream_v2_viewer_ended_at ON public.livestream_v2_viewer USING btree (ended_at)',
    'ix_livestream_v2_viewer_active': 'CREATE INDEX ix_livestream_v2_viewer_active ON public.livestream_v2_viewer USING btree (client_id, ended_at, last_seen_at)',
    'livestream_v2_generation_pkey': 'CREATE UNIQUE INDEX livestream_v2_generation_pkey ON public.livestream_v2_generation USING btree (id)',
    'ix_livestream_v2_generation_client_id': 'CREATE INDEX ix_livestream_v2_generation_client_id ON public.livestream_v2_generation USING btree (client_id)',
    'ix_livestream_v2_generation_state': 'CREATE INDEX ix_livestream_v2_generation_state ON public.livestream_v2_generation USING btree (state)',
    'ix_livestream_v2_generation_last_upload_at': 'CREATE INDEX ix_livestream_v2_generation_last_upload_at ON public.livestream_v2_generation USING btree (last_upload_at)',
    'ix_livestream_v2_generation_client_created': 'CREATE INDEX ix_livestream_v2_generation_client_created ON public.livestream_v2_generation USING btree (client_id, created_at)',
})
EXPECTED_SEQUENCES |= {
    'livestream_v2_agent_status_id_seq',
    'livestream_v2_viewer_id_seq',
}

# Step 42A: adopt the existing ClientFlow 1.2 Terminal-domain production tables.
from terminal_v2_schema_contract import (
    TERMINAL_V2_COLUMNS,
    TERMINAL_V2_CONSTRAINTS,
    TERMINAL_V2_INDEXES,
    TERMINAL_V2_TABLES,
)
EXPECTED_HEAD_REVISION = "20260816_45a_terminal_client"
EXPECTED_TABLES |= TERMINAL_V2_TABLES
EXPECTED_COLUMNS.update(TERMINAL_V2_COLUMNS)
EXPECTED_CONSTRAINTS.update(TERMINAL_V2_CONSTRAINTS)
EXPECTED_INDEXES.update(TERMINAL_V2_INDEXES)

EXPECTED_FINGERPRINT = "ee0981207368e32bcf5a52dd9c0f53bc5abed17582007772c9ed11970e151640"

# Step 46A: isolate Remote Desktop client identity, credentials and agent status.
from remote_desktop_v2_schema_contract import (
    REMOTE_DESKTOP_V2_COLUMNS,
    REMOTE_DESKTOP_V2_CONSTRAINTS,
    REMOTE_DESKTOP_V2_INDEXES,
    REMOTE_DESKTOP_V2_TABLES,
)
EXPECTED_HEAD_REVISION = "20260817_46a_remote_desktop_v2"
EXPECTED_TABLES |= REMOTE_DESKTOP_V2_TABLES
EXPECTED_COLUMNS.update(REMOTE_DESKTOP_V2_COLUMNS)
EXPECTED_CONSTRAINTS.update(REMOTE_DESKTOP_V2_CONSTRAINTS)
EXPECTED_INDEXES.update(REMOTE_DESKTOP_V2_INDEXES)
EXPECTED_FINGERPRINT = "25b0adcc69b26292ef1f6057cc1448bd7c39ff8accf44816daa1280f70f2f299"

# Step 47A: shared authenticated browser activity leases for cross-feature hold semantics.
from client_activity_schema_contract import (
    CLIENT_ACTIVITY_COLUMNS,
    CLIENT_ACTIVITY_CONSTRAINTS,
    CLIENT_ACTIVITY_INDEXES,
    CLIENT_ACTIVITY_TABLES,
)
EXPECTED_HEAD_REVISION = "20260818_47a_client_activity"
EXPECTED_TABLES |= CLIENT_ACTIVITY_TABLES
EXPECTED_COLUMNS.update(CLIENT_ACTIVITY_COLUMNS)
EXPECTED_CONSTRAINTS.update(CLIENT_ACTIVITY_CONSTRAINTS)
EXPECTED_INDEXES.update(CLIENT_ACTIVITY_INDEXES)
EXPECTED_FINGERPRINT = "0a1439d3cd3811ac842adeeb047cf545a438fd49ab432645cd05d02cb51567d9"

# Step 48A: lifecycle retention across permanent user deletion.
# Terminal session/grant history remains, so user references become nullable and
# use ON DELETE SET NULL. Legacy-origin RD/client-command references are migrated
# conditionally here and become exact reviewed objects at Step 49A.
EXPECTED_HEAD_REVISION = "20260818_48a_lifecycle"
EXPECTED_COLUMNS["terminal_session"]["requested_by_user_id"] = {
    "data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"
}
EXPECTED_COLUMNS["root_terminal_grant"]["user_id"] = {
    "data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"
}
EXPECTED_CONSTRAINTS["terminal_session_requested_by_user_id_fkey"] = 'FOREIGN KEY (requested_by_user_id) REFERENCES "user"(id) ON DELETE SET NULL'
EXPECTED_CONSTRAINTS["root_terminal_grant_user_id_fkey"] = 'FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE SET NULL'
EXPECTED_CONSTRAINTS["terminal_session_event_actor_user_id_fkey"] = 'FOREIGN KEY (actor_user_id) REFERENCES "user"(id) ON DELETE SET NULL'
EXPECTED_FINGERPRINT = "28c64908a2e87a07511497ee487961e7cae018b1106e4da26eb9710755fec83f"

# Step 49A: adopt active legacy-origin runtime tables into the exact head contract.
from adopted_runtime_schema_contract import (
    ADOPTED_RUNTIME_COLUMNS,
    ADOPTED_RUNTIME_CONSTRAINTS,
    ADOPTED_RUNTIME_INDEXES,
    ADOPTED_RUNTIME_TABLES,
)
EXPECTED_HEAD_REVISION = "20260819_49a_db_contract"
EXPECTED_TABLES |= ADOPTED_RUNTIME_TABLES
EXPECTED_COLUMNS.update(ADOPTED_RUNTIME_COLUMNS)
EXPECTED_CONSTRAINTS.update(ADOPTED_RUNTIME_CONSTRAINTS)
EXPECTED_INDEXES.update(ADOPTED_RUNTIME_INDEXES)
EXPECTED_FINGERPRINT = "12733459e3fe43611edfca307efd8bdcee9fc7b034ec3d9fb5fb83fd674c3d01"


# Step 50A: canonical shared foundations and fresh-enrollment persistence.
from canonical_foundations_schema_contract import (
    CANONICAL_FOUNDATION_COLUMNS,
    CANONICAL_FOUNDATION_CONSTRAINTS,
    CANONICAL_FOUNDATION_INDEXES,
    CANONICAL_FOUNDATION_TABLES,
)
EXPECTED_HEAD_REVISION = "20260819_50a_canonical"
EXPECTED_TABLES |= CANONICAL_FOUNDATION_TABLES
EXPECTED_COLUMNS.update(CANONICAL_FOUNDATION_COLUMNS)
_client_columns = dict(EXPECTED_COLUMNS["client"])
for _retired_column in (
    "pending_livestream_action",
    "pending_livestream_action_source",
    "livestream_control_plane_version",
    "school",
):
    _client_columns.pop(_retired_column, None)
EXPECTED_COLUMNS["client"] = _client_columns
EXPECTED_CONSTRAINTS.update(CANONICAL_FOUNDATION_CONSTRAINTS)
EXPECTED_CONSTRAINTS["users_role_check"] = "CHECK (role::text = ANY (ARRAY['superadmin'::character varying::text, 'admin'::character varying::text, 'bruger'::character varying::text, 'viewer'::character varying::text]))"
EXPECTED_INDEXES.update(CANONICAL_FOUNDATION_INDEXES)
EXPECTED_FINGERPRINT = "ecfdf8c5259574bba614060639b243533dd44f322e87249104f0ef3488603bdb"


# Step 51A: first-class ClientFlow deployment authority and stable update identity.
from clientflow_deployment_schema_contract import (
    CLIENTFLOW_DEPLOYMENT_COLUMNS,
    CLIENTFLOW_DEPLOYMENT_CONSTRAINTS,
    CLIENTFLOW_DEPLOYMENT_INDEXES,
    CLIENTFLOW_DEPLOYMENT_TABLES,
)
EXPECTED_HEAD_REVISION = "20260819_51a_update_control"
EXPECTED_TABLES |= CLIENTFLOW_DEPLOYMENT_TABLES
EXPECTED_COLUMNS.update(CLIENTFLOW_DEPLOYMENT_COLUMNS)
EXPECTED_CONSTRAINTS.update(CLIENTFLOW_DEPLOYMENT_CONSTRAINTS)
EXPECTED_INDEXES.update(CLIENTFLOW_DEPLOYMENT_INDEXES)
EXPECTED_FINGERPRINT = "7a69745e904741d54945eb19e90fc4c8fa66799793353d571432f6fee6d80b3b"

# Step 51B: isolated updater authentication replay/reprovision state.
from clientflow_update_auth_schema_contract import (
    CLIENTFLOW_UPDATE_AUTH_COLUMNS,
    CLIENTFLOW_UPDATE_AUTH_CONSTRAINTS,
    CLIENTFLOW_UPDATE_AUTH_INDEXES,
    CLIENTFLOW_UPDATE_AUTH_TABLES,
)
EXPECTED_HEAD_REVISION = "20260820_51b_update_auth"
EXPECTED_TABLES |= CLIENTFLOW_UPDATE_AUTH_TABLES
EXPECTED_COLUMNS.update(CLIENTFLOW_UPDATE_AUTH_COLUMNS)
EXPECTED_CONSTRAINTS.update(CLIENTFLOW_UPDATE_AUTH_CONSTRAINTS)
EXPECTED_INDEXES.update(CLIENTFLOW_UPDATE_AUTH_INDEXES)
EXPECTED_FINGERPRINT = "977a891ea299860d941b9ddb6a1a3c7ec4f9403b493611eb3c7a5ade9d36f222"

# Step 52A: retire split-brain legacy client liveness columns.
from client_liveness_schema_contract import CLIENT_LIVENESS_RETIRED_CLIENT_COLUMNS
EXPECTED_HEAD_REVISION = "20260822_52a_client_liveness"
_client_columns = dict(EXPECTED_COLUMNS["client"])
for _retired_column in CLIENT_LIVENESS_RETIRED_CLIENT_COLUMNS:
    if _retired_column not in _client_columns:
        raise RuntimeError(f"Step 52A expected legacy client column {_retired_column!r} before retirement")
    _client_columns.pop(_retired_column)
EXPECTED_COLUMNS["client"] = _client_columns
# Replaced below after deterministic contract fingerprint calculation.
EXPECTED_FINGERPRINT = "259e2623c532f66facb7a1083401355832f5f7d5e5e716c83337cf9daebcda03"

# Step 53A: canonical durable Display desired-state authority.
from display_authority_schema_contract import (
    DISPLAY_AUTHORITY_COLUMNS,
    DISPLAY_AUTHORITY_CONSTRAINTS,
    DISPLAY_AUTHORITY_INDEXES,
    DISPLAY_AUTHORITY_RETIRED_CLIENT_COLUMNS,
    DISPLAY_AUTHORITY_TABLES,
)
EXPECTED_HEAD_REVISION = "20260823_53a_display_authority"
EXPECTED_TABLES |= DISPLAY_AUTHORITY_TABLES
EXPECTED_COLUMNS.update(DISPLAY_AUTHORITY_COLUMNS)
_client_columns = dict(EXPECTED_COLUMNS["client"])
for _retired_column in DISPLAY_AUTHORITY_RETIRED_CLIENT_COLUMNS:
    if _retired_column not in _client_columns:
        raise RuntimeError(f"Step 53A expected legacy client column {_retired_column!r} before retirement")
    _client_columns.pop(_retired_column)
EXPECTED_COLUMNS["client"] = _client_columns
EXPECTED_CONSTRAINTS.update(DISPLAY_AUTHORITY_CONSTRAINTS)
EXPECTED_INDEXES.update(DISPLAY_AUTHORITY_INDEXES)
# Replaced below after deterministic contract fingerprint calculation.
EXPECTED_FINGERPRINT = "8b9e97bd26e43e242d0f948cb1927accb472a475a0d214baa6c9b6168bcc802e"
