"""Reviewed production catalog contract for Terminal-owned tables."""

TERMINAL_V2_TABLES = {
    "terminal_client",
    "terminal_credential",
    "terminal_agent_status",
    "root_terminal_grant",
    "terminal_session",
    "terminal_session_event",
}

TERMINAL_V2_COLUMNS = {
    "terminal_client": {
        "id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "display_name": {"data_type": "character varying", "default": None, "length": 255, "nullable": True, "udt_name": "varchar"},
        "status": {"data_type": "character varying", "default": "'approved'::character varying", "length": 32, "nullable": False, "udt_name": "varchar"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
    },
    "terminal_credential": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "secret_hash": {"data_type": "text", "default": None, "length": None, "nullable": False, "udt_name": "text"},
        "token_version": {"data_type": "integer", "default": "0", "length": None, "nullable": False, "udt_name": "int4"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "last_used_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "revoked_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
    },
    "terminal_agent_status": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "schema_version": {"data_type": "integer", "default": "1", "length": None, "nullable": False, "udt_name": "int4"},
        "observed_state": {"data_type": "character varying", "default": "'unknown'::character varying", "length": 80, "nullable": False, "udt_name": "varchar"},
        "status_payload": {"data_type": "jsonb", "default": None, "length": None, "nullable": False, "udt_name": "jsonb"},
        "agent_version": {"data_type": "character varying", "default": None, "length": 80, "nullable": True, "udt_name": "varchar"},
        "boot_id": {"data_type": "character varying", "default": None, "length": 128, "nullable": True, "udt_name": "varchar"},
        "credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "reported_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
    },
    "root_terminal_grant": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "terminal_session_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "user_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "grant_hash": {"data_type": "character varying", "default": None, "length": 64, "nullable": True, "udt_name": "varchar"},
        "step_up_verified_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "issued_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "expires_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "consumed_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "revoked_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "capability": {"data_type": "character varying", "default": "'terminal_root'::character varying", "length": 80, "nullable": False, "udt_name": "varchar"},
        "issued_to_credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": True, "udt_name": "varchar"},
    },
    "terminal_session": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "client_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "requested_by_user_id": {"data_type": "integer", "default": None, "length": None, "nullable": False, "udt_name": "int4"},
        "privilege_level": {"data_type": "character varying", "default": "'standard'::character varying", "length": 20, "nullable": False, "udt_name": "varchar"},
        "reason": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
        "source_ip": {"data_type": "character varying", "default": None, "length": 64, "nullable": True, "udt_name": "varchar"},
        "user_agent": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "authorized_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "connected_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "last_activity_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "expires_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "disconnected_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": True, "udt_name": "timestamp"},
        "status": {"data_type": "character varying", "default": "'authorized'::character varying", "length": 30, "nullable": False, "udt_name": "varchar"},
        "exit_code": {"data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"},
        "transcript_reference": {"data_type": "text", "default": None, "length": None, "nullable": True, "udt_name": "text"},
        "transcript_sha256": {"data_type": "character varying", "default": None, "length": 64, "nullable": True, "udt_name": "varchar"},
    },
    "terminal_session_event": {
        "id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "terminal_session_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": False, "udt_name": "varchar"},
        "event_type": {"data_type": "character varying", "default": None, "length": 80, "nullable": False, "udt_name": "varchar"},
        "actor_user_id": {"data_type": "integer", "default": None, "length": None, "nullable": True, "udt_name": "int4"},
        "credential_id": {"data_type": "character varying", "default": None, "length": 36, "nullable": True, "udt_name": "varchar"},
        "created_at": {"data_type": "timestamp without time zone", "default": None, "length": None, "nullable": False, "udt_name": "timestamp"},
        "details": {"data_type": "jsonb", "default": None, "length": None, "nullable": False, "udt_name": "jsonb"},
    },
}

TERMINAL_V2_CONSTRAINTS = {
    "ck_terminal_client_status": "CHECK (status::text = ANY (ARRAY['approved'::character varying, 'disabled'::character varying]::text[]))",
    "terminal_client_pkey": "PRIMARY KEY (id)",
    "ck_terminal_credential_token_version": "CHECK (token_version >= 0)",
    "terminal_credential_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES terminal_client(id)",
    "terminal_credential_pkey": "PRIMARY KEY (id)",
    "uq_terminal_credential_client": "UNIQUE (client_id)",
    "ck_terminal_agent_status_schema_version": "CHECK (schema_version >= 1)",
    "terminal_agent_status_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES terminal_client(id)",
    "terminal_agent_status_credential_id_fkey": "FOREIGN KEY (credential_id) REFERENCES terminal_credential(id)",
    "terminal_agent_status_pkey": "PRIMARY KEY (id)",
    "uq_terminal_agent_status_client": "UNIQUE (client_id)",
    "ck_root_terminal_grant_capability": "CHECK (capability::text = 'terminal_root'::text)",
    "ck_root_terminal_grant_expiry_order": "CHECK (expires_at > created_at)",
    "root_terminal_grant_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES terminal_client(id)",
    "root_terminal_grant_grant_hash_key": "UNIQUE (grant_hash)",
    "root_terminal_grant_issued_to_credential_id_fkey": "FOREIGN KEY (issued_to_credential_id) REFERENCES terminal_credential(id)",
    "root_terminal_grant_pkey": "PRIMARY KEY (id)",
    "root_terminal_grant_terminal_session_id_fkey": "FOREIGN KEY (terminal_session_id) REFERENCES terminal_session(id)",
    "root_terminal_grant_user_id_fkey": 'FOREIGN KEY (user_id) REFERENCES "user"(id)',
    "uq_root_terminal_grant_session": "UNIQUE (terminal_session_id)",
    "ck_terminal_session_expiry_order": "CHECK (expires_at > created_at)",
    "ck_terminal_session_privilege": "CHECK (privilege_level::text = ANY (ARRAY['standard'::character varying, 'root'::character varying]::text[]))",
    "ck_terminal_session_status": "CHECK (status::text = ANY (ARRAY['requested'::character varying, 'authorized'::character varying, 'connected'::character varying, 'disconnected'::character varying, 'expired'::character varying, 'revoked'::character varying, 'failed'::character varying]::text[]))",
    "terminal_session_client_id_fkey": "FOREIGN KEY (client_id) REFERENCES terminal_client(id)",
    "terminal_session_pkey": "PRIMARY KEY (id)",
    "terminal_session_requested_by_user_id_fkey": 'FOREIGN KEY (requested_by_user_id) REFERENCES "user"(id)',
    "terminal_session_event_actor_user_id_fkey": 'FOREIGN KEY (actor_user_id) REFERENCES "user"(id)',
    "terminal_session_event_credential_id_fkey": "FOREIGN KEY (credential_id) REFERENCES terminal_credential(id)",
    "terminal_session_event_pkey": "PRIMARY KEY (id)",
    "terminal_session_event_terminal_session_id_fkey": "FOREIGN KEY (terminal_session_id) REFERENCES terminal_session(id)",
}

TERMINAL_V2_INDEXES = {
    "terminal_client_pkey": "CREATE UNIQUE INDEX terminal_client_pkey ON public.terminal_client USING btree (id)",
    "ix_terminal_client_status": "CREATE INDEX ix_terminal_client_status ON public.terminal_client USING btree (status)",
    "terminal_credential_pkey": "CREATE UNIQUE INDEX terminal_credential_pkey ON public.terminal_credential USING btree (id)",
    "ix_terminal_credential_active": "CREATE INDEX ix_terminal_credential_active ON public.terminal_credential USING btree (client_id, revoked_at)",
    "ix_terminal_credential_last_used_at": "CREATE INDEX ix_terminal_credential_last_used_at ON public.terminal_credential USING btree (last_used_at)",
    "ix_terminal_credential_revoked_at": "CREATE INDEX ix_terminal_credential_revoked_at ON public.terminal_credential USING btree (revoked_at)",
    "uq_terminal_credential_client": "CREATE UNIQUE INDEX uq_terminal_credential_client ON public.terminal_credential USING btree (client_id)",
    "terminal_agent_status_pkey": "CREATE UNIQUE INDEX terminal_agent_status_pkey ON public.terminal_agent_status USING btree (id)",
    "ix_terminal_agent_status_reported_at": "CREATE INDEX ix_terminal_agent_status_reported_at ON public.terminal_agent_status USING btree (reported_at)",
    "uq_terminal_agent_status_client": "CREATE UNIQUE INDEX uq_terminal_agent_status_client ON public.terminal_agent_status USING btree (client_id)",
    "ix_root_terminal_grant_client_id": "CREATE INDEX ix_root_terminal_grant_client_id ON public.root_terminal_grant USING btree (client_id)",
    "ix_root_terminal_grant_consumed_at": "CREATE INDEX ix_root_terminal_grant_consumed_at ON public.root_terminal_grant USING btree (consumed_at)",
    "ix_root_terminal_grant_expires_at": "CREATE INDEX ix_root_terminal_grant_expires_at ON public.root_terminal_grant USING btree (expires_at)",
    "ix_root_terminal_grant_revoked_at": "CREATE INDEX ix_root_terminal_grant_revoked_at ON public.root_terminal_grant USING btree (revoked_at)",
    "ix_root_terminal_grant_user_id": "CREATE INDEX ix_root_terminal_grant_user_id ON public.root_terminal_grant USING btree (user_id)",
    "ix_root_terminal_grant_valid": "CREATE INDEX ix_root_terminal_grant_valid ON public.root_terminal_grant USING btree (client_id, expires_at, consumed_at, revoked_at)",
    "root_terminal_grant_grant_hash_key": "CREATE UNIQUE INDEX root_terminal_grant_grant_hash_key ON public.root_terminal_grant USING btree (grant_hash)",
    "root_terminal_grant_pkey": "CREATE UNIQUE INDEX root_terminal_grant_pkey ON public.root_terminal_grant USING btree (id)",
    "uq_root_terminal_grant_session": "CREATE UNIQUE INDEX uq_root_terminal_grant_session ON public.root_terminal_grant USING btree (terminal_session_id)",
    "ix_terminal_session_client_id": "CREATE INDEX ix_terminal_session_client_id ON public.terminal_session USING btree (client_id)",
    "ix_terminal_session_client_status": "CREATE INDEX ix_terminal_session_client_status ON public.terminal_session USING btree (client_id, status)",
    "ix_terminal_session_expires_at": "CREATE INDEX ix_terminal_session_expires_at ON public.terminal_session USING btree (expires_at)",
    "ix_terminal_session_expiry": "CREATE INDEX ix_terminal_session_expiry ON public.terminal_session USING btree (status, expires_at)",
    "ix_terminal_session_requested_by_user_id": "CREATE INDEX ix_terminal_session_requested_by_user_id ON public.terminal_session USING btree (requested_by_user_id)",
    "ix_terminal_session_status": "CREATE INDEX ix_terminal_session_status ON public.terminal_session USING btree (status)",
    "terminal_session_pkey": "CREATE UNIQUE INDEX terminal_session_pkey ON public.terminal_session USING btree (id)",
    "ix_terminal_session_event_created_at": "CREATE INDEX ix_terminal_session_event_created_at ON public.terminal_session_event USING btree (created_at)",
    "ix_terminal_session_event_event_type": "CREATE INDEX ix_terminal_session_event_event_type ON public.terminal_session_event USING btree (event_type)",
    "ix_terminal_session_event_timeline": "CREATE INDEX ix_terminal_session_event_timeline ON public.terminal_session_event USING btree (terminal_session_id, created_at)",
    "terminal_session_event_pkey": "CREATE UNIQUE INDEX terminal_session_event_pkey ON public.terminal_session_event USING btree (id)",
}
