d /etc/clientflow 0750 root root -
d /etc/clientflow/credentials 0700 root root -
d /etc/clientflow/root-terminal 0700 root root -
d /var/lib/clientflow 0755 root root -
d /var/lib/clientflow/status 0700 clientflow-status clientflow-status -
d /var/lib/clientflow/display-agent 0700 clientflow-display-agent clientflow-display-agent -
d /var/lib/clientflow/display 0750 clientflow-display clientflow-display-control -
d /var/lib/clientflow/livestream 0750 clientflow-livestream-runtime clientflow-livestream-control -
d /var/lib/clientflow/livestream-agent 0700 clientflow-livestream-agent clientflow-livestream-agent -
d /var/lib/clientflow/livestream-uploader 0750 clientflow-livestream-uploader clientflow-livestream-control -
d /var/lib/clientflow/remote-desktop 0700 clientflow-remote-desktop-agent clientflow-remote-desktop-agent -
d /var/lib/clientflow/remote-desktop/files 0700 clientflow-remote-desktop-agent clientflow-remote-desktop-agent -
d /var/lib/clientflow/remote-desktop/uploads 0700 clientflow-remote-desktop-agent clientflow-remote-desktop-agent -
d /var/lib/clientflow/terminal-agent 0700 clientflow-terminal-agent clientflow-terminal-agent -
d /var/lib/clientflow/terminal-session 0700 clientflow-terminal-session clientflow-terminal-session -
d /var/lib/clientflow/root-terminal 0700 root root -
d /var/lib/clientflow/system-agent 0700 clientflow-system-agent clientflow-system-agent -
d /var/lib/clientflow/system-broker 0700 root root -
d /run/clientflow 0755 root root -
