# Type Name                                  ID  GECOS                                   Home                                             Shell
g clientflow-display-control                 -
g clientflow-livestream-control              -
g clientflow-status                          -
g clientflow-display-agent                   -
g clientflow-livestream-agent                -
g clientflow-livestream-runtime              -
g clientflow-livestream-uploader             -
g clientflow-remote-desktop-agent            -
g clientflow-terminal-agent                  -
g clientflow-terminal-session                -
g clientflow-system-agent                    -
g clientflow-updater                         -
u clientflow-status                          -   "ClientFlow status agent"                 /var/lib/clientflow/status                    /usr/sbin/nologin
u clientflow-display-agent                   -   "ClientFlow display agent"                /var/lib/clientflow/display-agent             /usr/sbin/nologin
u clientflow-livestream-agent                -   "ClientFlow livestream agent"             /var/lib/clientflow/livestream-agent          /usr/sbin/nologin
u clientflow-livestream-runtime              -   "ClientFlow livestream runtime"           /var/lib/clientflow/livestream                /usr/sbin/nologin
u clientflow-livestream-uploader             -   "ClientFlow livestream uploader"          /var/lib/clientflow/livestream-uploader       /usr/sbin/nologin
u clientflow-remote-desktop-agent            -   "ClientFlow Remote Desktop agent"         /var/lib/clientflow/remote-desktop            /usr/sbin/nologin
u clientflow-terminal-agent                  -   "ClientFlow Terminal network agent"       /var/lib/clientflow/terminal-agent            /usr/sbin/nologin
u clientflow-terminal-session                -   "ClientFlow standard Terminal sessions"   /var/lib/clientflow/terminal-session          /usr/sbin/nologin
u clientflow-system-agent                    -   "ClientFlow system agent"                 /var/lib/clientflow/system-agent              /usr/sbin/nologin
u clientflow-updater                         -   "ClientFlow stable updater"               /var/lib/clientflow/updater                   /usr/sbin/nologin
m clientflow-display-agent clientflow-display-control
m clientflow-livestream-agent clientflow-livestream-control
m clientflow-livestream-runtime clientflow-livestream-control
m clientflow-livestream-uploader clientflow-livestream-control
